-- MySQL Script generated by MySQL Workbench
-- Sat Oct  7 18:52:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PsicologiaDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PsicologiaDB` ;

-- -----------------------------------------------------
-- Schema PsicologiaDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PsicologiaDB` DEFAULT CHARACTER SET utf8 ;
USE `PsicologiaDB` ;

-- -----------------------------------------------------
-- Table `PsicologiaDB`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PsicologiaDB`.`Users` ;

CREATE TABLE IF NOT EXISTS `PsicologiaDB`.`Users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PsicologiaDB`.`Alunos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PsicologiaDB`.`Alunos` ;

CREATE TABLE IF NOT EXISTS `PsicologiaDB`.`Alunos` (
  `idUser` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `curso` VARCHAR(255) NOT NULL,
  `fase` INT NOT NULL,
  `matricula` INT NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `nomeResponsavel` VARCHAR(255) NULL,
  `telefoneResponsavel` VARCHAR(20) NULL,
  `deficiencia` TEXT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`idUser`),
  CONSTRAINT `fk_Alunos_Users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `PsicologiaDB`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PsicologiaDB`.`Admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PsicologiaDB`.`Admins` ;

CREATE TABLE IF NOT EXISTS `PsicologiaDB`.`Admins` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PsicologiaDB`.`Servidors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PsicologiaDB`.`Servidors` ;

CREATE TABLE IF NOT EXISTS `PsicologiaDB`.`Servidors` (
  `Admins_id` BIGINT UNSIGNED NOT NULL,
  `superUser` TINYINT NULL,
  `setor` VARCHAR(255) NOT NULL,
  `siape` DECIMAL(15,0) NOT NULL,
  `telefone` DECIMAL(12,0) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`Admins_id`),
  INDEX `fk_Servidors_Admins1_idx` (`Admins_id` ASC),
  CONSTRAINT `fk_Servidors_Admins1`
    FOREIGN KEY (`Admins_id`)
    REFERENCES `PsicologiaDB`.`Admins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PsicologiaDB`.`Solicitacaos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PsicologiaDB`.`Solicitacaos` ;

CREATE TABLE IF NOT EXISTS `PsicologiaDB`.`Solicitacaos` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comentario` TEXT NOT NULL,
  `atdGrupo` TEXT NULL,
  `ativo` TEXT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PsicologiaDB`.`Agendamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PsicologiaDB`.`Agendamentos` ;

CREATE TABLE IF NOT EXISTS `PsicologiaDB`.`Agendamentos` (
  `Solicitacaos_id` BIGINT UNSIGNED NOT NULL,
  `dataEHora` TIMESTAMP NULL,
  `estado` CHAR(1) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`Solicitacaos_id`),
  INDEX `fk_agendamento_solicitacao1_idx` (`Solicitacaos_id` ASC),
  CONSTRAINT `fk_agendamento_solicitacao1`
    FOREIGN KEY (`Solicitacaos_id`)
    REFERENCES `PsicologiaDB`.`Solicitacaos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PsicologiaDB`.`Providencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PsicologiaDB`.`Providencias` ;

CREATE TABLE IF NOT EXISTS `PsicologiaDB`.`Providencias` (
  `idProvidencia` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`idProvidencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PsicologiaDB`.`Motivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PsicologiaDB`.`Motivos` ;

CREATE TABLE IF NOT EXISTS `PsicologiaDB`.`Motivos` (
  `idMotivos` INT NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`idMotivos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PsicologiaDB`.`Atendimentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PsicologiaDB`.`Atendimentos` ;

CREATE TABLE IF NOT EXISTS `PsicologiaDB`.`Atendimentos` (
  `Solicitacaos_id` BIGINT UNSIGNED NOT NULL,
  `idProvidencia` INT UNSIGNED NOT NULL,
  `idUsers` BIGINT UNSIGNED NOT NULL,
  `idMotivos` INT NOT NULL,
  `intervencao` TEXT NULL,
  `observacoes` VARCHAR(255) NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  INDEX `fk_Consulta_Encaminhamento1_idx` (`idProvidencia` ASC),
  PRIMARY KEY (`Solicitacaos_id`),
  INDEX `fk_Atendimentos_Motivos1_idx` (`idMotivos` ASC),
  CONSTRAINT `fk_Consulta_Encaminhamento1`
    FOREIGN KEY (`idProvidencia`)
    REFERENCES `PsicologiaDB`.`Providencias` (`idProvidencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atendimentos_Solicitacaos1`
    FOREIGN KEY (`Solicitacaos_id`)
    REFERENCES `PsicologiaDB`.`Solicitacaos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atendimentos_Motivos1`
    FOREIGN KEY (`idMotivos`)
    REFERENCES `PsicologiaDB`.`Motivos` (`idMotivos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PsicologiaDB`.`Data_Solicitacaos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PsicologiaDB`.`Data_Solicitacaos` ;

CREATE TABLE IF NOT EXISTS `PsicologiaDB`.`Data_Solicitacaos` (
  `idDataSolicitacao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Solicitacaos_id` BIGINT UNSIGNED NOT NULL,
  `periodo` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idDataSolicitacao`),
  INDEX `fk_DataSolicitacao_solicitacao1_idx` (`Solicitacaos_id` ASC),
  CONSTRAINT `fk_DataSolicitacao_solicitacao1`
    FOREIGN KEY (`Solicitacaos_id`)
    REFERENCES `PsicologiaDB`.`Solicitacaos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PsicologiaDB`.`Password_resets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PsicologiaDB`.`Password_resets` ;

CREATE TABLE IF NOT EXISTS `PsicologiaDB`.`Password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL,
  UNIQUE INDEX `token_UNIQUE` (`token` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PsicologiaDB`.`Solicitacaos_Alunos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PsicologiaDB`.`Solicitacaos_Alunos` ;

CREATE TABLE IF NOT EXISTS `PsicologiaDB`.`Solicitacaos_Alunos` (
  `Solicitacaos_id` BIGINT UNSIGNED NOT NULL,
  `Alunos_idUser` BIGINT UNSIGNED NOT NULL,
  `estado` CHAR(1) NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`Solicitacaos_id`, `Alunos_idUser`),
  INDEX `fk_Solicitacaos_has_Alunos_Alunos1_idx` (`Alunos_idUser` ASC),
  INDEX `fk_Solicitacaos_has_Alunos_Solicitacaos1_idx` (`Solicitacaos_id` ASC),
  CONSTRAINT `fk_Solicitacaos_has_Alunos_Solicitacaos1`
    FOREIGN KEY (`Solicitacaos_id`)
    REFERENCES `PsicologiaDB`.`Solicitacaos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitacaos_has_Alunos_Alunos1`
    FOREIGN KEY (`Alunos_idUser`)
    REFERENCES `PsicologiaDB`.`Alunos` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `PsicologiaDB`.`Users`
-- -----------------------------------------------------
START TRANSACTION;
USE `PsicologiaDB`;
INSERT INTO `PsicologiaDB`.`Users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `updated_at`, `created_at`) VALUES (1, 'user', 'user@user.com.br', NULL, '$2y$10$QHF9vHYC8Gk6kW.7tLFf7.KZw82PVzvGAXry0P9EMO1.2SjCqXmZ6', NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `PsicologiaDB`.`Alunos`
-- -----------------------------------------------------
START TRANSACTION;
USE `PsicologiaDB`;
INSERT INTO `PsicologiaDB`.`Alunos` (`idUser`, `curso`, `fase`, `matricula`, `telefone`, `nomeResponsavel`, `telefoneResponsavel`, `deficiencia`, `updated_at`, `created_at`) VALUES (1, 'cc', 2, 123, '123', 'fulano', '123', 'sim', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `PsicologiaDB`.`Admins`
-- -----------------------------------------------------
START TRANSACTION;
USE `PsicologiaDB`;
INSERT INTO `PsicologiaDB`.`Admins` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `updated_at`, `created_at`) VALUES (1, 'Admin', 'admin@admin.com.br', NULL, '$2y$10$Lan4n3N1dAa8cUFhT9OMVuXjzmh9u9ucbux2.9LO/2nYiqeQT068G', NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `PsicologiaDB`.`Servidors`
-- -----------------------------------------------------
START TRANSACTION;
USE `PsicologiaDB`;
INSERT INTO `PsicologiaDB`.`Servidors` (`Admins_id`, `superUser`, `setor`, `siape`, `telefone`, `updated_at`, `created_at`) VALUES (1, 1, 'Núcleo Pedagógico', 123123, 123123, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `PsicologiaDB`.`Solicitacaos`
-- -----------------------------------------------------
START TRANSACTION;
USE `PsicologiaDB`;
INSERT INTO `PsicologiaDB`.`Solicitacaos` (`id`, `comentario`, `atdGrupo`, `ativo`, `updated_at`, `created_at`) VALUES (1, 'Estou com problemas...', 'sim', 'sim', '2023-06-30 20:00:00', '2023-06-30 20:00:00');
INSERT INTO `PsicologiaDB`.`Solicitacaos` (`id`, `comentario`, `atdGrupo`, `ativo`, `updated_at`, `created_at`) VALUES (2, 'Estou com problemas...', 'não', 'não', '2023-06-30 20:00:00', '2023-06-30 20:00:00');

COMMIT;


-- -----------------------------------------------------
-- Data for table `PsicologiaDB`.`Agendamentos`
-- -----------------------------------------------------
START TRANSACTION;
USE `PsicologiaDB`;
INSERT INTO `PsicologiaDB`.`Agendamentos` (`Solicitacaos_id`, `dataEHora`, `estado`, `updated_at`, `created_at`) VALUES (1, '2019-08-20 08:00:00', 'A', '2019-08-19 17:00:00', '2019-08-19 17:00:00');

COMMIT;


-- -----------------------------------------------------
-- Data for table `PsicologiaDB`.`Providencias`
-- -----------------------------------------------------
START TRANSACTION;
USE `PsicologiaDB`;
INSERT INTO `PsicologiaDB`.`Providencias` (`idProvidencia`, `descricao`, `updated_at`, `created_at`) VALUES (1, 'Nenhuma', NULL, NULL);
INSERT INTO `PsicologiaDB`.`Providencias` (`idProvidencia`, `descricao`, `updated_at`, `created_at`) VALUES (2, 'Aguardando reagendamento', NULL, NULL);
INSERT INTO `PsicologiaDB`.`Providencias` (`idProvidencia`, `descricao`, `updated_at`, `created_at`) VALUES (3, 'Matrícula cancelada', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `PsicologiaDB`.`Data_Solicitacaos`
-- -----------------------------------------------------
START TRANSACTION;
USE `PsicologiaDB`;
INSERT INTO `PsicologiaDB`.`Data_Solicitacaos` (`idDataSolicitacao`, `Solicitacaos_id`, `periodo`) VALUES (1, 1, '2019-08-20 08:00:00');
INSERT INTO `PsicologiaDB`.`Data_Solicitacaos` (`idDataSolicitacao`, `Solicitacaos_id`, `periodo`) VALUES (2, 1, '2019-08-20 13:00:00');
INSERT INTO `PsicologiaDB`.`Data_Solicitacaos` (`idDataSolicitacao`, `Solicitacaos_id`, `periodo`) VALUES (3, 1, '2019-08-21 08:00:00');
INSERT INTO `PsicologiaDB`.`Data_Solicitacaos` (`idDataSolicitacao`, `Solicitacaos_id`, `periodo`) VALUES (4, 1, '2019-08-21 13:00:00');

COMMIT;


-- -----------------------------------------------------
-- Data for table `PsicologiaDB`.`Solicitacaos_Alunos`
-- -----------------------------------------------------
START TRANSACTION;
USE `PsicologiaDB`;
INSERT INTO `PsicologiaDB`.`Solicitacaos_Alunos` (`Solicitacaos_id`, `Alunos_idUser`, `estado`, `updated_at`, `created_at`) VALUES (1, 1, 'A', NULL, NULL);

COMMIT;

